### ISSUE TITLE
false permissions for the nextcloud logs?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1078]
I've got a lot of that type of errors in my nextcloud logs: (it seems like I have already so many errors in my log, that it tries to create a new file, named nextcloud.log.1)
`rename(/var/log/nextcloud/nextcloud.log,/var/log/nextcloud/nextcloud.log.1): Permission denied at /var/www/nextcloud/lib/public/Log/RotationTrait.php#53`

I think this is becaue you just chown `nextcloud.log` but not the complete folder in the script https://github.com/nextcloud/vm/blob/master/static/setup_secure_permissions_nextcloud.sh

`chown -R "${htuser}":"${htgroup}" "${VMLOGS}"`

should solve these errors.
But I don't know if that brings any security issues with it.

**Comment by szaimen** [comment]
this should probably then also get adjusted in the https://github.com/nextcloud/vm/blob/master/apps/fail2ban.sh script

**Comment by enoch85** [comment]
There are no harm in setting the folder to www-data:www-data, I can prepare a PR for that later.

**Comment by szaimen** [comment]
So I would say this issue is already solved? I have manually changed the owner of the folder to www-data:www-data and directly all error messages were gone.

**Comment by enoch85** [comment]
Thanks for closing.

**Comment by Klemens2** [comment]
Sorry, I have the same error messages very often and I'm still quite a beginner with nextcloud.

Can you give me the exact code to solve this? And after this, is it necessary to change the ...fail2ban.sh-script ir is this done via updates in the meantime? 

I have Nextcloud 19 on a VM (image by enoch 85 downloaded last year...).

Thanks in advance!

**Comment by enoch85** [comment]
@Klemens2 

The permissions are already set: https://github.com/nextcloud/vm/blob/master/static/setup_secure_permissions_nextcloud.sh#L54

Please run `sudo bash /var/scripts/setup_secure_permissions_nextcloud.sh`to fix the issue.

**Comment by Klemens2** [comment]
Thank you very much, Daniel!!!

I did this step and it ran as shown in the following snapshot. But unfortunatly, the error is still resuming, every five minutes...
![grafik](https://user-images.githubusercontent.com/43281637/88111274-ec274a00-cbad-11ea-978e-26244da5af70.png)

Have you another idea what to do?

**Comment by enoch85** [comment]
@Klemens2 `sudo chown www-data:www-data /var/log/nextcloud -R`

**Comment by Klemens2** [comment]
Thank you, it worked :-)

**Comment by enoch85** [comment]
@Klemens2 Can you please test the latest script?

`wget https://raw.githubusercontent.com/nextcloud/vm/master/static/setup_secure_permissions_nextcloud.sh && sudo bash setup_secure_permissions_nextcloud.sh`

Also, please give me the output of `sudo ls -l /var/log/nextcloud`

Thanks!

**Comment by Klemens2** [comment]
Sorry for my late reply, I've been on vacation until now.
1)
![grafik](https://user-images.githubusercontent.com/43281637/89345387-9a9bb680-d6a7-11ea-831b-1acca994e36f.png)

2)
![grafik](https://user-images.githubusercontent.com/43281637/89345493-d0d93600-d6a7-11ea-89d4-21085ed06f15.png)

Thank you!
