### ISSUE TITLE
Update to redis 5.0.0 causes Internal Server Error

### ISSUE THREAD

**Issue by ccghad** [nextcloud/vm#868]
Hi,

we use Nextcloud VM with Nextcloud 15.0.7 and PHP7.0.
After running /var/scripts/update.sh a new version of redis (5.0.0) was installed.
This leads to the following log messages in the apache2 error.log:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: undefined symbol: json_globals in Unknown on line 0`

Redis 5.0.0 was released on July 2nd and seems to be a new major release and seems to be no longer working. Compile of redis showed no error.
Downgrading to redis-4.3.0 solves the problem. 

Other people also hit the problem:
[Internal Server Error: Redis not available for local cache](https://help.nextcloud.com/t/internal-server-error-redis-not-available-for-local-cache/55929)

Thank you & best regards,
Stefan

## Server configuration

**Nextcloud server version:** (see your admin page)
15.0.7.0

**Server OS** (Ubuntu server is default)
Ubuntu server

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install

## Network
No

**Is port 80 and/or 443 open?**
Yes

#### Log file (/mnt/ncdata/nextcloud.log)
```
{"reqId":"5L026lECXGVYIQv4DVef","level":3,"time":"2019-07-08T19:42:43+00:00","remoteAddr":"92.192.141.11","user":"--","app":"PHP","method":"GET","url":"\/status
.php","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php\/20151012\/redis.so' - \/usr\/lib\/php\/20151012\/redis.so: undefined symbol: json
_globals at Unknown#0","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.2git (Nextcloud)","version":"15.0.7.0"}
{"reqId":"vemdtZ5X5hVOv7UCDqdi","level":3,"time":"2019-07-08T19:43:04+00:00","remoteAddr":"172.20.6.4","user":"--","app":"remote","method":"GET","url":"\/status
.php","message":{"Exception":"OC\\HintException","Message":"Memcache \\OC\\Memcache\\Redis not available for local cache","Code":0,"Trace":[{"file":"\/var\/www\
/nextcloud\/lib\/private\/Server.php","line":511,"function":"__construct","class":"OC\\Memcache\\Factory","type":"->","args":["8747fb0988708c15f40e34747df9bc0b"
,{"__class__":"OC\\Log"},"\\OC\\Memcache\\Redis","\\OC\\Memcache\\Redis","\\OC\\Memcache\\Redis"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src
\/Pimple\/Container.php","line":118,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var
\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["O
C\\Memcache\\Factory"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\Sim
pleContainer","type":"->","args":["OC\\Memcache\\Factory"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":165
,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OC\\Memcache\\Factory"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/P
imple\/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["***
 sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["MemCacheFactory"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["MemCacheFactory"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Server.php","line":1533,"function":"query","class":"OC\\ServerContainer","type":"->","args":["MemCacheFactory"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Server.php","line":697,"function":"getMemCacheFactory","class":"OC\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OC\\App\\AppManager"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OC\\App\\AppManager"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":165,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OC\\App\\AppManager"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["AppManager"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["AppManager"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Server.php","line":1723,"function":"query","class":"OC\\ServerContainer","type":"->","args":["AppManager"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/app.php","line":342,"function":"getAppManager","class":"OC\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/app.php","line":113,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":654,"function":"loadApps","class":"OC_App","type":"::","args":[["session"]]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/status.php","line":36,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Memcache\/Factory.php","Line":99,"Hint":"Is the matching PHP module installed and enabled?","CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"15.0.7.0"}
```

**Comment by enoch85** [comment]
Hi!

Thanks for posting this issue.

This is know and I posted information on Twitter some time ago that the server needed to be rebooted when that happens. 

It's happens due to the major version change in Redis. 

So, as long as you only ran the update script, and didn't do any other modifications, a plain reboot of the server should solve the issue. Have you tried that?

**Comment by enoch85** [comment]
Possible fix: https://github.com/nextcloud/vm/pull/869

**Comment by enoch85** [comment]
Tested what was wrong and fixed it with suggested PR

**Comment by enoch85** [comment]
@ccghad Thanks for letting me know! Apparently it works on Ubuntu 18.04 but not older versions.

**Comment by ccghad** [comment]
> So, as long as you only ran the update script, and didn't do any other modifications, a plain reboot of the server should solve the issue. Have you tried that?

@enoch85 Thank you for your feedback. Actually we rebooted the server after the problem showed up but it did not solve it.
Anyway, thank you for your patch to the update script!

**Comment by enoch85** [comment]
Hi again, I accidentally upgrade a server to the latest Redis, and it worked after a reboot. So it seems to be random.

```
administrator@nextcloud:~$ sudo pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
redis   5.0.0   stable
administrator@nextcloud:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
